### ISSUE TITLE
CPU goes up to 100% when this package is running

### ISSUE THREAD

**Issue by suryast** [jaebradley/atomify#30] opened 2017-04-07 01:33 UTC
Hi,

Somehow this package is causing my CPU usage to be 100% all the time when I have atom editor and spotify running. Also, it is really hard to quit Spotify when multiple Atom windows are open – spotify keeps relaunching. It might just be my computer or a bug. Great app otherwise, but for now I will need to uninstall this.

**Comment by jcollinsnw** [comment] 2017-04-11 20:11
I've noticed that it somehow forks infinite Apple Script processes and causes this. I even try to kill all the osascript processes in the command line and all of the processes exhaust the number of file handlers that Mac OS can handle. Nothing can be opened, no new commands can run and the system is as good as locked.

Output when I try to run a command in terminal:

-bash: /dev/null: Too many open files
-bash: /dev/null: Too many open files
-bash: cannot make pipe for command substitution: Too many open files
-bash: cannot make pipe for command substitution: Too many open files

Only way of fixing this was to boot into safemode on the Mac and uninstall atomify. Sadly I have Atom start up automatically. But since it was locking up my whole system I couldn't disable the login item or uninstall the package.

A Spotify package for a text editor should never be able to bring down a whole machine but somehow Atomify manages to do this. Kudos. And beware people wishing to use this.

**Comment by carroux** [comment] 2017-04-14 07:35
Looks like a duplicate of #17

**Closed** 2017-07-08 10:55 UTC
